### ISSUE TITLE
New Branch Seeds - Git Pull without Request

### ISSUE THREAD

**Issue by rdevans87** [kelsie-c/pettrax#2]
Hey gang, 

My apologies. It only makes sense that I would make the first mistake. I created a new branch called Seeds and accidentally did a git pull without first making a pull request. Not quite used to having to do that yet! I don't think it messed anything up in the main branch, but I don't know enough about git branching and CLI to be sure if this will cause an issue when I try to commit these changes later. I'll definitely be more careful moving forward. I decided to practice  I think this fits into the "good first issue" label. I just wanted to make you all aware! I took a screenshot of my terminal, so you can see exactly what happened.  

![Screen Shot 2021-04-29 at 12 12 51 AM](https://user-images.githubusercontent.com/74195719/116501835-db63dd00-a87f-11eb-90d2-ce2931de37cb.png)

**Comment by dishdesigner** [comment]
I don't think you could mess anything up in the remote Main branch because Kelsie has it locked down so code must be reviewed and approved before being merged into Main.

And the word "pull" is often confusing in Git because it is always directional....
- If you "pull" from the remote repo, you are copying down all the GitHub repo's code into your own local code base.
- But a "pull request" goes the other direction....you are asking the owner of the GitHub repo to do a pull from your local code base into the remote repo's code base online.

Your first instinct to do a "pull" BEFORE creating a "pull request" is exactly correct:
- You should always pull from the remote Main branch to make sure all the core app's files are updated in your local repo before asking the GitHub remote repo owner to pull your branch code into the remote and merge it into Main.
- Pulling down from Main first ensures that none of the files in the main app outside your branch will create merge conflicts when you commit and then push your branch code up.....Only the branch's files should be different from the online repo.

**Comment by rdevans87** [comment]
Thank you for the clarification! I feel much better now. See y’all in class this evening. Have a good day!
